<?php
$update  = $this->group ? true : false;
?>
<?php
$baseUrlCdn = \Bootstrap::getCdn().'/a/';
?>
<!DOCTYPE html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>admin</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $baseUrlCdn; ?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $baseUrlCdn; ?>css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?php echo $baseUrlCdn; ?>css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $baseUrlCdn; ?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?php echo $baseUrlCdn; ?>html5shiv.js"></script>
    <script src="<?php echo $baseUrlCdn; ?>respond.min.js"></script>
    <![endif]-->

</head>
<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="javascript:;">管理后台</a>
        </div>


        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li class="dropdown">
                    <a href="/index/index/group" data-toggle="collapse" data-target="#demo">
                        <i class="fa fa-fw fa-wrench"></i>
                        分组管理
                    </a>
                </li>
                <li class="dropdown">
                    <a href="/index/index/point" data-toggle="collapse" data-target="#demo">
                        <i class="fa fa-fw fa-wrench"></i>
                        标识管理
                    </a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    分组管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('index/index/group') ?>">分组
                        </a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> <?php if ($update) { ?> 编辑 <?php } else { ?> 新增 <?php } ?>
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">

            <div class="col-lg-6">

                <form role="form" action="<?php
                    echo \Bootstrap::getUrl('index/index/groupupdate');
                 ?>">

                    <div class="form-group">
                        <label>名字</label>
                        <input class="form-control" name="name" value="<?php if ($update) {
                            echo $this->group['name'];
                        } ?>"/>

                        <p class="help-block">名字</p>
                    </div>

                    <div class="form-group">
                        <label>排序</label>
                        <input class="form-control" name="sort" value="<?php if ($update) {
                            echo $this->group['sort'];
                        } ?>"/>

                        <p class="help-block">排序</p>
                    </div>


                    <input type="hidden" name="id" value="<?php if ($update) {
                        echo $this->group['id'];
                    } ?>"/>

                    <input type="hidden" name="updatetype" value="<?php echo $update ? 'update' : 'add';?>" />

                    <button type="submit" class="btn btn-default">提交</button>
                    <button type="reset" class="btn btn-default">取消</button>

                </form>

            </div>

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->

<!-- jQuery -->



<!-- /#wrapper -->

<!-- jQuery -->
<script src="<?php echo $baseUrlCdn; ?>js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $baseUrlCdn; ?>js/bootstrap.min.js"></script>

<!-- Morris Charts JavaScript -->
<script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/raphael.min.js"></script>
<script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/morris.min.js"></script>
<script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/morris-data.js"></script>


<!-- /#page-wrapper -->
</body>



</html>