<?php
$baseUrlCdn = \Bootstrap::getCdn().'/a/';
?>
<!DOCTYPE html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>admin</title>

        <!-- Bootstrap Core CSS -->
        <link href="<?php echo $baseUrlCdn; ?>css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="<?php echo $baseUrlCdn; ?>css/sb-admin.css" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="<?php echo $baseUrlCdn; ?>css/plugins/morris.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="<?php echo $baseUrlCdn; ?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="<?php echo $baseUrlCdn; ?>html5shiv.js"></script>
        <script src="<?php echo $baseUrlCdn; ?>respond.min.js"></script>
        <![endif]-->

    </head>
    <body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:;">管理后台</a>
            </div>


            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="dropdown">
                        <a href="/index/index/group" data-toggle="collapse" data-target="#demo">
                            <i class="fa fa-fw fa-wrench"></i>
                            分组管理
                        </a>
                    </li>
                        <li class="dropdown">
                            <a href="/index/index/point" data-toggle="collapse" data-target="#demo">
                                <i class="fa fa-fw fa-wrench"></i>
                                标识管理
                            </a>
                        </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            分组管理
                        </h1>
                        <ol class="breadcrumb">

                            <li class="active">
                                <i class="fa fa-edit"></i> 列表(<?php echo $this->total ?>)
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->


                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <div class="widget-body">
                            <div class="table-toolbar">
                                <a id="editabledatatable_new" href="<?php echo \Bootstrap::getUrl('index/index/groupreplace') ?>"
                                   class="btn btn-default">
                                    新增
                                </a>
                            </div>
                            <table class="table table-striped table-hover table-bordered" id="editabledatatable">
                                <thead>
                                <tr role="row">
                                    <th>
                                        id
                                    </th>
                                    <th>
                                        名字
                                    </th>
                                    <th>
                                        排序
                                    </th>

                                    <th>
                                        添加时间
                                    </th>
                                    <th>
                                        操作
                                    </th>
                                </tr>
                                </thead>
                                <tbody>

                                <?php
                                if ($this->groups) {
                                    foreach ($this->groups as $v) {
                                        $item = $v->toArray();
                                        ?>
                                        <tr>
                                            <td>
                                                <?php echo $item['id'] ?>
                                                </td>
                                            <td>
                                                <?php echo $item['name'] ?>
                                            </td>
                                            <td><?php echo $item['sort'] ?></td>
                                            <td><?php echo date('Y-m-d H:i:s',$item['creattime']) ?></td>
                                            <td>
                                                <a href="<?php echo \Bootstrap::getUrl('index/index/groupreplace/') . '/?id=' . $item['id']; ?>"
                                                   class="btn btn-info btn-xs edit"><i class="fa fa-edit"></i> Edit</a>
                                                <a href="<?php echo \Bootstrap::getUrl('index/index/groupdelete/') . '/?id=' . $item['id']; ?>"
                                                   class="btn btn-danger btn-xs delete"><i class="fa fa-trash-o"></i>
                                                    Delete</a>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->



    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="<?php echo $baseUrlCdn; ?>js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $baseUrlCdn; ?>js/bootstrap.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/raphael.min.js"></script>
    <script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/morris.min.js"></script>
    <script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/morris-data.js"></script>


    <!-- /#page-wrapper -->
    </body>



</html>
