<?php
$baseUrlCdn = \Bootstrap::getCdn().'/a/';
?>
<!DOCTYPE html>
    <head>
        <title>Login One</title>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="<?php echo $baseUrlCdn;?>css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $baseUrlCdn;?>css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $baseUrlCdn;?>css/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $baseUrlCdn;?>css/templatemo_style.css" rel="stylesheet" type="text/css">
    </head>
    <body class="templatemo-bg-gray">

    <div class="container">
        <div class="col-md-12">
            <h1 class="margin-bottom-15">登录</h1>
            <form class="form-horizontal templatemo-container templatemo-login-form-1 margin-bottom-30" role="form" action="/index/index/checklogin" method="post">
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="control-wrapper">
                            <label for="username" class="control-label fa-label"><i class="fa fa-user fa-medium"></i></label>
                            <input type="text" class="form-control" name="username" id="username" placeholder="用户名">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="control-wrapper">
                            <label for="password" class="control-label fa-label"><i class="fa fa-lock fa-medium"></i></label>
                            <input type="password" class="form-control" name="pwd" id="password" placeholder="密码">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <div class="control-wrapper">
                            <input type="submit" value="登录" class="btn btn-info">
                        </div>
                    </div>
                </div>
                <hr>
            </form>

        </div>
    </div>
    </body>


</html>
