<?php
$update  = $this->point ? true : false;
$baseUrlCdn = \Bootstrap::getCdn().'/a/';
?>
<!DOCTYPE html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>admin</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $baseUrlCdn; ?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $baseUrlCdn; ?>css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?php echo $baseUrlCdn; ?>css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $baseUrlCdn; ?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?php echo $baseUrlCdn; ?>html5shiv.js"></script>
    <script src="<?php echo $baseUrlCdn; ?>respond.min.js"></script>
    <![endif]-->

</head>
<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="javascript:;">管理后台</a>
        </div>


        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li class="dropdown">
                    <a href="/index/index/group" data-toggle="collapse" data-target="#demo">
                        <i class="fa fa-fw fa-wrench"></i>
                        分组管理
                    </a>
                </li>
                <li class="dropdown">
                    <a href="/index/index/point" data-toggle="collapse" data-target="#demo">
                        <i class="fa fa-fw fa-wrench"></i>
                        标识管理
                    </a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    标识管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('index/index/index') ?>">标识
                        </a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> <?php if ($update) { ?> 编辑 <?php } else { ?> 新增 <?php } ?>
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">

            <div class="col-lg-6">

                <form role="form" method="post" enctype="multipart/form-data" action="<?php
                    echo \Bootstrap::getUrl('index/index/pointupdate');
                 ?>">

                    <div class="form-group">
                        <label>名字</label>
                        <input class="form-control" name="name" value="<?php if ($update) {
                            echo $this->point['name'];
                        } ?>"/>

                        <p class="help-block">名字</p>
                    </div>
                    <div class="form-group">
                        <label>分组</label>
                        <select class="form-control" name="group_id">
                            <option value="0">请选择</option>
                            <?php
                            foreach ($this->grouplist as $id => $name) {
                                ?>
                                <option
                                    value="<?php echo $id ?>" <?php if ($update && $this->point['group_id'] == $id) { ?> selected<?php } ?> ><?php echo $name ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>


                    <div class="form-group">
                        <label>手机</label>
                        <input class="form-control" name="phone" value="<?php if ($update) {
                            echo $this->point['phone'];
                        } ?>"/>

                        <p class="help-block">手机</p>
                    </div>

                    <div class="form-group">
                        <label>File input</label>
                        <input name="picurl" type="file">
                        <input type="hidden" name="MAX_FILE_SIZE" value="2000000">
                        <?php if ($update && $this->point['pics']) {
                            ?>
                            <img src=" <?php echo $this->point['pics'] ?>"/>
                        <?php
                        }
                        ?>
                    </div>



                    <div class="form-group">
                        <label>地址</label>
                        <input class="form-control" name="address" value="<?php if ($update) {
                            echo $this->point['address'];
                        } ?>"/>

                        <p class="help-block">地址</p>
                    </div>
                    <div class="form-group">
                        <label>跳转链接</label>
                        <input class="form-control" name="url_address" value="<?php if ($update) {
                            echo $this->point['url_address'];
                        } ?>"/>

                        <p class="help-block">跳转链接</p>
                    </div>

                    <div class="form-group">
                        <label>简介</label>

                        <textarea rows="10" cols="100" name = 'remark'>
                            <?php if ($update) {
                                echo $this->point['remark'];
                            } ?>
                        </textarea>

                        <p class="help-block">简介</p>
                    </div>

                    <div class="form-group">
                        <label>坐标</label>
                        <input class="form-control" name="point" value="<?php if ($update) {
                            echo $this->point['point'];
                        } ?>"/>

                        <p class="help-block">坐标</p>
                    </div>
                    <div style="width: 800px; height: 500px;" id="allmap">


                    </div>




                    <input type="hidden" name="id" value="<?php if ($update) {
                        echo $this->point['id'];
                    } ?>"/>

                    <input type="hidden" name="updatetype" value="<?php echo $update ? 'update' : 'add';?>" />

                    <button type="submit" class="btn btn-default">提交</button>
                    <button type="reset" class="btn btn-default">取消</button>

                </form>

            </div>

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->

<!-- jQuery -->



<!-- /#wrapper -->

<!-- jQuery -->
<script src="<?php echo $baseUrlCdn; ?>js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $baseUrlCdn; ?>js/bootstrap.min.js"></script>

<!-- Morris Charts JavaScript -->
<script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/raphael.min.js"></script>
<script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/morris.min.js"></script>
<script src="<?php echo $baseUrlCdn; ?>js/plugins/morris/morris-data.js"></script>

<script type="text/javascript" src="http://api.map.baidu.com/api?key=59db371659c04947a1ff044e80565718&v=1.1&services=false"></script>
<script type="text/javascript">
    var map = new BMap.Map("allmap");
    var point = new BMap.Point(118.149957, 24.493976);
    map.centerAndZoom(point, 12);
    var top_left_control = new BMap.ScaleControl({ anchor: BMAP_ANCHOR_TOP_LEFT });// 左上角，添加比例尺
    var top_left_navigation = new BMap.NavigationControl();  //左上角，添加默认缩放平移控件
    var top_right_navigation = new BMap.NavigationControl({ anchor: BMAP_ANCHOR_TOP_RIGHT, type: BMAP_NAVIGATION_CONTROL_SMALL }); //右上角，仅包含平移和缩放按钮
    /*缩放控件type有四种类型:
     BMAP_NAVIGATION_CONTROL_SMALL：仅包含平移和缩放按钮；BMAP_NAVIGATION_CONTROL_PAN:仅包含平移按钮；BMAP_NAVIGATION_CONTROL_ZOOM：仅包含缩放按钮*/

    //添加控件和比例尺
    map.addControl(top_left_control);
    map.addControl(top_left_navigation);
    map.addControl(top_right_navigation);
    //单击获取点击的经纬度
    map.addEventListener("click", function (e) {
        $('input[name="point"]').val(e.point.lng + "," + e.point.lat);
//        alert(e.point.lng + "," + e.point.lat);
    });
</script>
<!-- /#page-wrapper -->
</body>



</html>